---
kind: pipeline
name: publish

steps:
  - name: npm
    image: plugins/npm
    settings:
      username: amanbolat
      token:
        from_secret: crossasia_npm_token
      email: amanbolat@crossasia.ru
      registry: https://npm.crossasia.ru